### PR TITLE
[CSL-430] Add tests to 'HashNodeId' module

### PR DESCRIPTION
**Pull request by rockbmb**

### CODE REVIEW

**Comment by rockbmb** [comment]
@zakharvoit @georgeee CSL-430, low priority but review when possible.

**Review by zakharvoit — APPROVED** [review]
Good

**Comment by rockbmb** [comment]
@zakharvoit Mind merging this one, then? Can't/Shouldn't do it myself. It has no conflicts, should be 2 minutes, at most.

**Comment by zakharvoit** [comment]
@rockbmb Let @georgeee review it, it is low priority, maybe he knows some other things to check in tests

**Review by georgeee — APPROVED** [review]

**Pull request merged**
